name: Test workflow
run-name: "Push by: ${{ github.actor }}"
on: 
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        options:
          - Ubuntu
          - macOS
  push:
jobs:
  test_job:
    name: "Pushed with following SHA: ${{ github.sha }}"
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: if step
        if: ${{ github.event_name != 'push' }}
        run: echo ${{ github.event_name }}
      
      - name: echo
        run: echo Hello, World!

      - run: ls -la


  test_job2:
    runs-on: ubuntu-latest 
    steps:
      - run: echo Hello, World!
    
    
